const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '../../../..');
const spec = JSON.parse(fs.readFileSync(path.join(root, 'projects/multimedia/shot-on-purpose/assessment/forms-spec.json'), 'utf8'));
const code = fs.readFileSync(path.join(__dirname, 'bound-project/Code.js'), 'utf8');
const sync = fs.readFileSync(path.join(__dirname, 'bound-project/TechnologyEvidenceMapSync.js'), 'utf8');
const requiredSkills = new Set(['PS-CAM-01','PS-LGT-02','PS-ADJ-01','PS-TON-01','PS-LAY-01','PS-TRN-01','PS-TYP-01','PS-OUT-01','GD-HIE-01','GD-AUD-01','GD-COL-01','GD-CRIT-01']);
assert.equal(spec.project_id, 'mm12-26-s03-bundle');
assert.equal(spec.knowledge_check.items.length, 8);
assert.deepEqual(spec.teacher_evidence.checkpoints.map(x => x.step_id), Array.from({length:21},(_,i)=>`step-${i+1}`));
assert.deepEqual(new Set(spec.teacher_evidence.checkpoints.flatMap(x=>x.skill_ids)), requiredSkills);
assert.deepEqual(new Set(spec.teacher_evidence.checkpoints.map(x=>x.lesson_id)), new Set(Array.from({length:9},(_,i)=>`mm12-26-s03-d${String(i+1).padStart(2,'0')}`)));
assert.match(code, /Support used \(separate from achievement\)/);
assert.match(code, /LI-D08 - Plan and Organize/);
assert.match(code, /evidence_type: 'Support'/);
assert.match(code, /level: ''/);
assert.match(code, /outcome_codes: ''/);
assert.match(code, /mapCheckpointChoices_/);
assert.match(code, /'lesson_id'/);
assert.match(sync, /if\(stream==='support'\)/);
assert.match(sync, /ev\.support_detail=payload\.support_detail/);
const routerBody = code.slice(code.indexOf('function onAssessmentSpreadsheetSubmit'), code.indexOf('function routeStudentSpreadsheetSubmit_'));
const appendBody = code.slice(code.indexOf('function appendEvidence_'), code.indexOf('function scoreQuizItem_'));
assert.doesNotMatch(routerBody, /waitLock/);
assert.match(appendBody, /lock\.waitLock\(30000\)/);
assert.ok(appendBody.indexOf('lock.releaseLock()') < appendBody.indexOf('emOnEvidenceAppended_'));
console.log('MM12 Sprint 3 Form contract passed.');
