"""Build original teaching briefs and a private English companion from reviewed sources."""
from pathlib import Path
from html import escape
import json
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'outputs/gold-standard-2026'; PRIVATE=ROOT/'private'; PRIVATE.mkdir(exist_ok=True)
sources=[
 {'id':'BRADLEY','title':'Mastering Adobe Photoshop 2026, 2nd edition — Gary Bradley','edition':'Published December 2025; 2026 title; ISBN 9781806021710','role':'Primary creative extension source','read':'Contents, preface, mock-up workflow and selected surrealist workflows inspected. Other project anchors below are contents-level references until the agent reads the chapter.','location':'User-supplied PDF; keep in the private fabrication project.','url':'https://www.packtpub.com/en-gb/product/mastering-adobe-photoshop-2026-9781806021710'},
 {'id':'KLASSEN','title':'Adobe Photoshop — Der professionelle Einstieg — Robert Klaßen','edition':'13th updated and expanded edition, 2026; ISBN 9783367115846','role':'Workshop reference and mask teaching companion','read':'Contents and layer-mask section pp. 172–181 inspected in German. Selected English companion supplied separately, not a complete 505-page translation.','location':'User-supplied German PDF and private English companion.','url':'https://www.rheinwerk-verlag.de/6311'},
 {'id':'TRICKS','title':'Adobe Photoshop Tricks and Tips','edition':'118-page scanned PDF; publisher branding BDM Publications; edition/year unverified','role':'Visual idea bank','read':'Cover/intro and contents visually inspected. Full workshops not OCR-verified or rehearsed.','location':'User-supplied PDF. Read the actual workshop before using its steps.','url':''},
 {'id':'EASTON','title':'Adobe Photoshop 2024 Guide for Beginners — Denvey Easton','edition':'2024 title; supplied EPUB','role':'Optional additional explanation for beginners','read':'Package metadata and chapter structure inspected. Technical instructions not verified chapter by chapter.','location':'User-supplied EPUB. Validate a selected passage before recommending it.','url':''},
 {'id':'ADOBE','title':'Adobe Photoshop documentation','edition':'Live documentation checked 14 September 2026','role':'Current control behaviour and troubleshooting','read':'Mask and transformation behaviour checked against Adobe documentation.','location':'Official online documentation.','url':'https://helpx.adobe.com/photoshop/desktop/create-masks/layer-masks/add-layer-masks.html'}]
# These are original brief ideas, not reproductions of the books' assignments or assets.
projects=[
 ('World inside an object','KLASSEN','pp. 172–181; PDF and printed page numbers agree','Place a different imagined environment inside a photographed everyday object.','Layer masks, edge repair, explaining conceal versus deletion','Own object photograph and own or licensed landscape','Move the boundary across an overlapping foreground object; repair without erasing source pixels.'),
 ('A brand on three surfaces','BRADLEY','Chapter 5; magazine mock-up pp. 164–168 inspected','Adapt an original identity to a flat poster, a curved package and a photographed surface.','Smart objects, transform, blending, consistent identity','Original logo and three photographed blank objects','Replace the identity once, then explain which instances update and why.'),
 ('Impossible local landmark','BRADLEY','Chapter 14, pp. 469–512; selected workflows inspected','Combine a familiar place with an impossible scale change that conveys a clear idea.','Masking, light direction, perspective, intentional meaning','Own local photograph and licensed subject cutout','Change the light direction and defend the revisions needed for a believable composite.'),
 ('A texture with a purpose','BRADLEY','Chapter 10, pp. 345–369; contents anchor','Build a reusable texture that supports a particular mood without obscuring the message.','Pattern design, gradients, contrast, controlled repetition','Original marks or photographed textures','Reuse the texture at a different size and identify visible repetition or readability problems.'),
 ('Type that behaves like material','BRADLEY','Chapter 9, graffiti effect pp. 337–343; contents anchor','Create an editable title that suggests a chosen material or environment.','Typography, effects, hierarchy, non-destructive layers','Original wording and self-made texture','Change the title length and repair the layout without rasterising the source type.'),
 ('A custom brush ecosystem','BRADLEY','Chapter 11, pp. 371–401; contents anchor','Design a brush family and use it to suggest movement, weather or a habitat.','Brush presets, scale, spacing, selective application','Own silhouette or mark','Explain and adjust one brush property for a visibly different context.'),
 ('Two exposures, one intentional image','BRADLEY','Chapter 13, pp. 433–467; contents anchor','Blend two captures to make a deliberate visual statement while retaining editability.','Alignment, masks, tonal relationships','Two own or licensed exposures','Explain a halo or seam, repair it and compare the result at normal viewing size.'),
 ('One campaign, three screens','BRADLEY','Chapter 7, From Pixels to Post; contents anchor','Reframe an original campaign for three aspect ratios while retaining hierarchy.','Artboards, typography, export, audience','Original campaign art and supplied output dimensions','Add a fourth unusually narrow format without stretching the artwork.'),
 ('A loop that explains','BRADLEY','Chapter 8, Creating Animated GIFs and Videos; contents anchor','Make a short loop explaining a process or showing a purposeful transformation.','Timeline, timing, visual sequence, export','Original stills or a short licensed clip','Revise the timing based on a viewer comprehension check.'),
 ('An editorial colour treatment','TRICKS','Stylised Portraits pp. 58–67; contents anchor','Use a self-portrait, consenting subject or licensed portrait to communicate a chosen editorial mood.','Adjustment layers, selection, colour intent','Consented or licensed portrait','Provide an alternative treatment and explain its effect without equating retouching with personal worth.'),
 ('Atmosphere from ordinary weather','TRICKS','Warm Up an Overcast Day pp. 106–115; contents anchor','Create two contrasting moods from the same location image.','Colour balance, local adjustment, visual interpretation','Own location photograph','Keep a neutral reference and explain the boundary between expressive editing and factual representation.'),
 ('An event poster under constraint','BRADLEY','Chapter 6, Creating Printed Marketing Collateral; contents anchor','Design an event poster with a clear audience, hierarchy and production specification.','Layout, typography, print/export checks','Original event brief and owned imagery','Adapt to a new audience or output size while preserving the required information.')]
base='''<style>body{font:17px/1.6 system-ui;color:#203c3d;background:#f5f7f2;margin:0}main{max-width:1050px;margin:auto;padding:36px 24px}h1{font:clamp(32px,5vw,54px)/1.12 Georgia,serif}h2{margin-top:38px}a{color:#12695c}article,section{background:white;border:1px solid #cbd7cc;border-radius:8px;padding:24px;margin:18px 0}small{color:#4b635b}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#edf2e8;padding:22px}button{padding:12px 18px;background:#235f54;color:white;border:0;border-radius:5px;font:inherit;cursor:pointer}table{border-collapse:collapse;width:100%}td,th{padding:10px;border-bottom:1px solid #ccd7ce;text-align:left}.table{overflow:auto}@media print{body{background:white}article{break-inside:avoid}button{display:none}}</style>'''
prompt='''Create a complete teaching package for [project title] in [MM12 or COM11]. Use the supplied source section, verified course outcome wording and I-can statement. Read the actual source pages before writing steps. Do not treat a contents entry as a completed technical review.

Class duration: 60-minute core plus a 15-minute extension, pending timetable confirmation. Photoshop: current Creative Cloud; record the exact installed version. Prerequisites: opening/saving a PSD, layers and safe file handling. List any further prerequisite this project needs.

Build three routes with the same core criteria: guided practice with checkpoints; a creative choice brief; an independent changed brief requiring transfer. Let students choose useful support and let the teacher adjust it. Do not assign fixed learning-style labels. Keep supported practice separate from the scored independent attempt.

Deliver student HTML, an editable decision workbook, original or authorised starter assets, an editable layered teacher exemplar, a changed retest, teacher notes and a manifest. Keep teacher answers separate. Use original compositions; do not redistribute textbook images or copied chapters in the student/public package.

For each criterion, map the course outcome, I-can statement, skill ID and the Product/Observation/Conversation evidence that makes it visible. Students record what skill they used, what they did, what they learned, their artifact reference, help used and next action. The teacher records a distinct skill judgment and, only when warranted, a separate outcome judgment. No automatic percentage or readiness conversion.

Require a design rationale and at least one repair or changed condition. Specify the four local readiness anchors only for the task family being assessed. Preserve individual evidence during group work. Include an accessible route and record access support without lowering the band solely because of that support.

Rehearse the exact files in the installed Photoshop version, reopen the PSD, inspect layer/mask/type editability and export dimensions, and provide genuine application screenshots. Report tested steps, untested steps, actual timings and unresolved issues separately. Do not declare a learner-timing trial or inter-rater moderation complete without those observations.
'''
(OUT/'Creative_Fabrication_Prompt.md').write_text('# Creative Photoshop fabrication brief\n\n'+prompt)
cards=''.join(f'<article id="project-{i+1}"><small>{escape(s)} · {escape(anchor)}</small><h2>{i+1}. {escape(title)}</h2><p>{escape(brief)}</p><p><b>Skills:</b> {escape(skills)}</p><p><b>Assets:</b> {escape(assets)}</p><p><b>Independent change:</b> {escape(change)}</p><p><b>Evidence:</b> layered product, observed repair and a short individual explanation. Ask: What did you learn that you can use again?</p><small>Original project proposal. Source anchor supplied; this complete lesson has not yet been fabricated or rehearsed.</small></article>' for i,(title,s,anchor,brief,skills,assets,change) in enumerate(projects))
source_html=''.join(f'<article><h3>{escape(s["title"])}</h3><p>{escape(s["edition"])}</p><p><b>{escape(s["role"])}</b> — {escape(s["read"])}</p><small>{escape(s["location"])}</small>'+ (f'<p><a href="{escape(s["url"])}">Publisher or documentation reference</a></p>' if s['url'] else '')+'</article>' for s in sources)
html='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Creative Photoshop Library</title>'+base+'<main><a href="../../help/index.html#fabrication">← Field guide</a><h1>Creative Photoshop library</h1><p>Use a dependable foundation, then give the learner a real design decision, a changed condition and something worth explaining.</p><section><h2>Choose the support, keep the criteria</h2><p><b>Guided practice:</b> short demonstrated technique with checkpoints. <b>Creative choice:</b> choose subject, audience or visual direction. <b>Independent transfer:</b> solve a changed brief and explain a repair. These are flexible routes, not labels assigned to learners.</p><p>Classroom in a Book can remain the foundation source. Bradley adds creative production depth; Klaßen adds practical workshops. No additional purchase is needed to begin with the supplied books.</p><p>The source books stay private. The public release contains original teaching briefs and source references. The English companion covers selected mask pages, not the whole German book.</p></section><h2>Sources and what has been checked</h2>'+source_html+'<h2>Twelve creative starting points</h2>'+cards+'<section><h2>Copy a fabrication brief</h2><p>Choose one project above, then add its exact outcome, skill IDs, source pages and authorised assets.</p><button id="copy">Copy brief</button> <a href="Creative_Fabrication_Prompt.md" download>Download Markdown</a><p id="status" role="status"></p><pre id="prompt">'+escape(prompt)+'</pre></section></main><script>document.querySelector("#copy").onclick=async()=>{try{await navigator.clipboard.writeText(document.querySelector("#prompt").textContent);document.querySelector("#status").textContent="Brief copied."}catch(e){document.querySelector("#status").textContent="Select the brief text or download the Markdown file."}}</script></html>'
(OUT/'Creative_Photoshop_Library.html').write_text(html)
(OUT/'Photoshop_Source_Catalog.json').write_text(json.dumps({'reviewedAt':'2026-09-14','sources':sources,'projects':[dict(zip(['title','source','anchor','brief','skills','assets','transfer'],p)) for p in projects]},indent=2,ensure_ascii=False))
print("Built creative library, source catalogue and fabrication prompt. The private English companion is maintained separately.")
