import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const BASE=process.env.EVIDENCE_MAP_URL||'http://127.0.0.1:8796';
const OUT='/private/tmp/evidence-map-runtime';
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{if(!localStorage.getItem('assignment-qa-seeded')){localStorage.setItem('tos_rosters_v1',JSON.stringify({MM12:[{id:'AS-QA',name:'Assignment Test Learner',grade:12,color:'#123456'}],IBDS:[{id:'AS-QA-DS',name:'DS Test Learner',grade:12,color:'#123456'}]}));localStorage.setItem('assignment-qa-seeded','true');}});
await page.goto(BASE);await page.selectOption('#courseSel','MM12');
const route=async r=>{const link=page.locator('#nav a[data-route="'+r+'"]');if(await link.isVisible())await link.click();else await page.selectOption('#areaNav',r);};
const state=()=>page.evaluate(()=>window.EvidenceStudio.exportState());
await route('assignments');assert.equal(await page.locator('[data-open-assignment]').count(),27);
assert.match(await page.locator('#assignmentDetail').innerText(),/specified task rubric is not available/);
await page.click('[data-assignment-capture]');assert.equal(await page.inputValue('#evAttempt'),'mm12-26-s01-a1');assert.equal(await page.locator('#evOutcomeLevel').isDisabled(),true);
await page.fill('#evNote','Synthetic observation on a task awaiting its rubric');await page.check('#evVerified');await page.locator('#evidenceForm button[type="submit"], #evidenceForm > .actions > button').first().click();
assert.equal((await state()).evidence[0].assignmentId,'mm12-26-s01-a1');assert.equal((await state()).evidence[0].rubricId,null);
await route('assignments');await page.click('[data-open-assignment="mm12-26-s01-a2"]');assert.match(await page.locator('#assignmentDetail').innerText(),/Image integration/);
await page.locator('#assignmentDetail').screenshot({path:OUT+'/assignment-detail-tested.png'});
const wait=page.waitForEvent('download');await page.click('[data-assignment-brief]');const d=await wait;const brief=await fs.readFile(await d.path(),'utf8');assert.match(brief,/mm12-citrus-rush-rubric-v1/);assert.ok(!brief.includes('Assignment Test Learner'));assert.match(brief,/mm12-26-s02-d01/);
await page.click('[data-assignment-capture]');assert.equal(await page.inputValue('#evAttempt'),'mm12-26-s01-a2');assert.equal(await page.locator('#evOutcomeLevel').isDisabled(),false);
await page.selectOption('#evMethod','Observation');await page.fill('#evArtifact','synthetic-citrus.psd');await page.fill('#evNote','Independently repaired an edge <img src=x onerror="window.injected=true">');await page.fill('#evNext','Explain the changed overlap');await page.check('#evVerified');
const outcome=await page.locator('#evOutcome option').nth(1).getAttribute('value');await page.selectOption('#evOutcome',outcome);await page.selectOption('#evOutcomeLevel','3');await page.locator('#evidenceForm > .actions > button').click();
const saved=(await state()).evidence.at(-1);assert.equal(saved.assignmentId,'mm12-26-s01-a2');assert.equal(saved.rubricId,'mm12-citrus-rush-rubric-v1');assert.equal(saved.outcomeLinks[0].rubricVersion,saved.rubricId);
await page.reload();await route('assignments');await page.click('[data-open-assignment="mm12-26-s01-a2"]');assert.match(await page.locator('#assignmentDetail').innerText(),/synthetic-citrus.psd/);assert.equal(await page.evaluate(()=>window.injected),undefined);
await route('profile');assert.equal(await page.locator('#clearAssignment').count(),0,'Assignment context must not leak after leaving its capture flow');
await route('courseplan');const linked=page.locator('[data-lesson-assignment="mm12-26-s01-a2"]').first();await linked.evaluate(b=>b.closest('details').open=true);await linked.click();assert.match(await page.locator('#assignmentTitle').innerText(),/Citrus/);
await page.click('[data-assignment-sprint]');assert.equal(await page.locator('.sprint-catalogue > section').count(),9);await page.locator('[data-sprint-assignments="MM12-S01"]').click();assert.ok(await page.locator('[data-open-assignment]').count()>0);
await page.selectOption('#assignmentStatus','ready');assert.equal(await page.locator('[data-open-assignment]').count(),0);assert.match(await page.locator('.assignment-list').innerText(),/No assignments match/);
await page.selectOption('#courseSel','IBDS');await route('assignments');assert.equal(await page.locator('[data-open-assignment]').count(),57);assert.ok(!(await page.locator('.studio').innerText()).includes('synthetic-citrus.psd'));
await page.selectOption('#courseSel','COM11');await route('assignments');assert.equal(await page.locator('[data-open-assignment]').count(),27);
await page.selectOption('#courseSel','CP12');await route('assignments');assert.match(await page.locator('.studio').innerText(),/no consolidated assignment catalogue/i);
await page.selectOption('#courseSel','MM12');await route('assignments');await page.screenshot({path:OUT+'/assignments-desktop.png'});
const overflow=[];await page.setViewportSize({width:390,height:844});for(const r of ['assignments','sprintoverview']){await route(r);const diff=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);if(diff>1)overflow.push({r,diff});}
await route('assignments');await page.screenshot({path:OUT+'/assignments-mobile.png'});
assert.deepEqual(overflow,[]);assert.deepEqual(errors,[]);
const report={status:'pass',checks:['111 assignment entries across three courses','rubric resolution and missing-rubric capture guard','linked lesson and cross-sprint navigation','assignment provenance and shared outcome evidence','save and reload','student-data-free fabrication download','course isolation','HTML escaping','CP12 fallback','390px assignment and sprint layouts'],errors,overflow};
await fs.writeFile(OUT+'/assignment-browser-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();
