const {test}=require('node:test');
const assert=require('node:assert/strict');
const C=require('../netlify/functions/_shared/evidence-core.cjs');
const {makeService,deploymentEnv}=require('../netlify/functions/_shared/evidence-service.cjs');
class MemoryStore{constructor(){this.data=new Map();}async get(k){return this.data.get(k)||null;}async setJSON(k,v){this.data.set(k,structuredClone(v));}async list({prefix=''}){return {blobs:[...this.data.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key}))};}}
const raw=(x={})=>({event_id:'fixture-event-01',learner_id:'lrn_fixture_01',course_id:'MM12',project_id:'PS-TRUCK-AD',canonical_id:'TA-OBS-01',outcome_codes_raw:'MM12 1.1',evidence_type_raw:'Observation+Conversation',stream:'evidence',teacher_note:'Located the mask, repaired the edge, explained the change.',step_id:'TA-S03',level_raw:'3 - Secure',independence_raw:'Guided',teacher_verified:'false',timestamp:'2026-09-23T12:00:00Z',...x});
const review=(x={})=>({review_id:'review-01',learner_id:'lrn_fixture_01',course_id:'MM12',outcome_id:'ns-mm12-2015-1.1',achievement:'Secure',support:'Guided',comment:'Uses editable masks to refine the edge. Next, test a different source image.',rationale:'Observation and explanation show purposeful control of the edit.',evidence_ids:['fixture-event-01'],parents:[],...x});
function harness(){const store=new MemoryStore(),legacy=new MemoryStore();const env=n=>({EVIDENCE_MAP_INGEST_SECRET:'google-test-secret',EVIDENCE_MAP_READ_SECRET:'reader-test-secret',EVIDENCE_MAP_TEACHER_SECRET:'teacher-test-secret'})[n];const handle=makeService({env,store,legacy});
  const call=async(action,body,who='teacher',query='course_id=MM12')=>{const token={teacher:'teacher-test-secret',google:'google-test-secret',reader:'reader-test-secret'}[who];const res=await handle(new Request('https://example.test/.netlify/functions/evidence-bridge?action='+action+'&'+query,{method:body?'POST':'GET',headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})}));return {status:res.status,headers:res.headers,data:await res.json()};};return {store,legacy,handle,call};}
test('strict booleans, note/step preservation and combined observation/conversation',()=>{const e=C.normalizeEvent(raw());assert.equal(e.teacher_verified,false);assert.equal(e.source_teacher_claim,false);assert.equal(e.teacher_note,raw().teacher_note);assert.equal(e.step_id,'TA-S03');assert.deepEqual(e.methods,['Observation','Conversation']);assert.equal(e.support_signal.band,'Guided');assert.equal(e.band,'Secure');});
test('unknown outcomes are held for mapping and cannot become judgments',()=>{const e=C.normalizeEvent(raw({outcome_codes_raw:'MM12 9.9'}));assert.equal(e.mapping_status,'needs_mapping');assert.throws(()=>C.normalizeReview(review(),[],[e],'Teacher'),/Evidence must belong/);});
test('canonical and historical image IDs resolve without shifting historical sound IDs',()=>{assert.equal(C.outcome('mm12-o1','MM12').outcome_id,'ns-mm12-2015-1.1');assert.equal(C.outcome('MM12 3.1','MM12').outcome_id,'ns-mm12-2015-3.1');assert.equal(C.outcome('mm12-o11','MM12'),undefined);});
test('shared Truck Ad outcomes stay attached to the right course without losing template references',()=>{const source=raw({outcome_codes_raw:'MM12 1.1;CT11 4.4'});const e=C.normalizeEvent(source);assert.equal(e.mapping_status,'mapped');assert.deepEqual(e.outcomes.map(o=>o.outcome_id),['ns-mm12-2015-1.1']);assert.equal(e.other_course_outcomes[0].course_id,'COM11');assert.equal(C.scopeEventToCourse(e).other_course_outcomes.length,1);assert.equal(C.normalizeReview(review(),[],[e],'Teacher').achievement,'Secure');const com=C.normalizeEvent({...source,course_id:'COM11'});assert.equal(com.outcomes[0].outcome_code,'COM11-4-4');assert.equal(com.other_course_outcomes[0].course_id,'MM12');});
test('existing mixed-course records are repaired in the view without changing their stored revision or hiding unknown codes',()=>{const historical={...C.normalizeEvent(raw()),outcomes:[{raw:'MM12 1.1',outcome_id:'ns-mm12-2015-1.1',outcome_code:'MM12-1.1'},{raw:'CT11 4.4',outcome_id:null,outcome_code:'CT11 4.4'}],mapping_status:'needs_mapping'};const fixed=C.scopeEventToCourse(historical);assert.equal(fixed.mapping_status,'mapped');assert.equal(fixed.revision_id,historical.revision_id);assert.equal(historical.outcomes.length,2);assert.equal(C.scopeEventToCourse({...historical,outcomes:[...historical.outcomes,{raw:'MM12 9.9',outcome_id:null}]}).mapping_status,'needs_mapping');});
test('missing quiz scores remain unscored, never incorrect by default',()=>{const e=C.normalizeEvent(raw({stream:'knowledge',level_raw:'4'}));assert.equal(e.is_correct,null);assert.equal(e.band,null);});
test('support does not cap achievement; knowledge alone cannot justify achievement',()=>{const e=C.normalizeEvent(raw());assert.equal(C.normalizeReview(review({achievement:'Extending'}),[],[e],'Teacher').achievement,'Extending');assert.throws(()=>C.normalizeReview(review(),[],[C.normalizeEvent(raw({stream:'knowledge'}))],'Teacher'),/Evidence must belong/);});
test('cross-course, cross-learner, malformed ID and invalid timestamp are rejected',()=>{assert.throws(()=>C.normalizeEvent(raw({event_id:'../escape'})));assert.throws(()=>C.normalizeEvent(raw({timestamp:'yesterday'})));assert.throws(()=>C.normalizeReview(review({learner_id:'lrn_other'}),[],[C.normalizeEvent(raw())],'Teacher'));assert.throws(()=>C.normalizeReview(review({course_id:'COM11'}),[],[C.normalizeEvent(raw())],'Teacher'));});
test('Google intake is idempotent and teacher decisions survive evidence replay',async()=>{const h=harness();assert.equal((await h.call('events',{events:[raw()]},'google')).data.results['fixture-event-01'].ok,true);const second=await h.call('events',{events:[raw()]},'google');assert.equal(second.data.results['fixture-event-01'].dedup,true);assert.equal((await h.call('review',review())).status,200);await h.call('events',{events:[raw({source_revision:2,teacher_note:'Corrected note'})]},'google');const s=(await h.call('snapshot')).data;assert.equal(s.events.length,1);assert.equal(s.events[0].teacher_note,'Corrected note');assert.equal(s.progress[0].achievement,'Secure');assert.equal(s.progress[0].support,'Guided');});
test('a repeat review request is idempotent; reused ID with different content conflicts',async()=>{const h=harness();await h.call('events',{events:[raw()]},'google');await h.call('review',review());assert.equal((await h.call('review',review())).data.dedup,true);assert.equal((await h.call('review',review({achievement:'Extending'}))).status,409);});
test('a stale device is rejected; simultaneous branches remain visible as a conflict',async()=>{const h=harness();await h.call('events',{events:[raw()]},'google');await h.call('review',review());assert.equal((await h.call('review',review({review_id:'stale'}))).status,409);const a=C.normalizeReview(review(),[],[C.normalizeEvent(raw())],'Teacher'),b=C.normalizeReview(review({review_id:'parallel',achievement:'Developing'}),[],[C.normalizeEvent(raw())],'Teacher');const p=C.progress([a,b])[0];assert.equal(p.status,'conflict');assert.equal(p.achievement,null);assert.equal(p.revision_ids.length,2);});
test('a conflicted raw event cannot be graded silently',()=>{const a=C.normalizeEvent(raw()),b=C.normalizeEvent(raw({teacher_note:'Different same-revision payload'}));const e=C.eventHeads([a,b])[0];assert.equal(e.conflict,true);assert.throws(()=>C.normalizeReview(review(),[],[e],'Teacher'));});
test('ingest and read credentials cannot write teacher judgments',async()=>{const h=harness();assert.equal((await h.call('snapshot',null,'none')).status,401);assert.equal((await h.call('review',review(),'google')).status,403);assert.equal((await h.call('review',review(),'reader')).status,403);assert.equal((await h.call('events',{events:[raw()]},'reader')).status,403);});
test('preview authentication never falls back to production credentials',()=>{const read=name=>({EVIDENCE_MAP_TEACHER_SECRET:'live',EVIDENCE_MAP_PREVIEW_TEACHER_SECRET:'fixture'})[name];const live=deploymentEnv('outcome-evidence-map.netlify.app',read),preview=deploymentEnv('fixture--outcome-evidence-map.netlify.app',read);assert.equal(live('CONTEXT'),'production');assert.equal(preview('CONTEXT'),'deploy-preview');assert.equal(live('EVIDENCE_MAP_TEACHER_SECRET'),'live');assert.equal(preview('EVIDENCE_MAP_TEACHER_SECRET'),'fixture');assert.equal(deploymentEnv('fixture--outcome-evidence-map.netlify.app',name=>name==='EVIDENCE_MAP_TEACHER_SECRET'?'live':undefined)('EVIDENCE_MAP_TEACHER_SECRET'),undefined);});
test('Google progress is a one-way mirror of the teacher decision, with no raw event echo',async()=>{const h=harness();await h.call('events',{events:[raw()]},'google');await h.call('review',review());const before=h.store.data.size,p=(await h.call('progress',null,'google')).data;assert.equal(p.source,'evidence_map');assert.equal(p.progress[0].comment,review().comment);assert.equal(h.store.data.size,before);assert.equal((await h.call('snapshot',null,'google')).status,403);});
test('roster is private and Google-owned, without email transmission',async()=>{const h=harness(),b={course_id:'MM12',learners:[{learner_id:'lrn_fixture_01',display_name:'Fictional Learner',active:true,student_email:'discard@example.invalid'}]};assert.equal((await h.call('roster',b,'teacher')).status,403);assert.equal((await h.call('roster',b,'google')).status,200);const r=(await h.call('snapshot')).data.roster;assert.equal(r.learners[0].display_name,'Fictional Learner');assert.equal(r.learners[0].student_email,undefined);});
test('teacher login creates an HttpOnly session; cross-origin posts are rejected',async()=>{const h=harness(),r=await h.call('login',{access_key:'teacher-test-secret'},'none');assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Strict/);const res=await h.handle(new Request('https://example.test/?action=review',{method:'POST',headers:{Origin:'https://untrusted.test'},body:'{}'}));assert.equal(res.status,403);});
test('field capture requires an approved rubric, so mismatched drafts stay on device',async()=>{const h=harness();assert.equal((await h.call('events',{events:[raw()]})).status,400);});
test('empty courses and service outages never substitute fictional evidence',async()=>{const h=harness();assert.deepEqual((await h.call('snapshot')).data.events,[]);h.store.list=async()=>{throw Error('offline');};assert.equal((await h.call('snapshot')).status,503);});
test('preview stores are isolated by host even when the platform deployment ID is missing or reused',()=>{
 const env=()=> 'shared-platform-id';
 assert.equal(deploymentEnv('preview-one--outcome-evidence-map.netlify.app',env)('DEPLOY_ID'),'preview-one');
 assert.equal(deploymentEnv('preview-two--outcome-evidence-map.netlify.app',env)('DEPLOY_ID'),'preview-two');
 assert.equal(deploymentEnv('outcome-evidence-map.netlify.app',env)('CONTEXT'),'production');
});
