const {test}=require('node:test');const assert=require('node:assert/strict');
const C=require('../netlify/functions/_shared/evidence-core.cjs');
const S=require('../netlify/functions/_shared/evidence-service.cjs');
class MemoryStore{constructor(){this.data=new Map();}async get(k){return structuredClone(this.data.get(k)||null);}async setJSON(k,v){this.data.set(k,structuredClone(v));}async list({prefix=''}){return {blobs:[...this.data.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key}))};}}
function setup(){const store=new MemoryStore();const env=k=>({EVIDENCE_MAP_TEACHER_SECRET:'teacher',EVIDENCE_MAP_INGEST_SECRET:'google'})[k];const handle=S.makeService({env,store,legacy:new MemoryStore()});const call=async(action,body,who='teacher',query='course_id=MM12')=>{const r=await handle(new Request('https://example.test/?action='+action+'&'+query,{method:body?'POST':'GET',headers:{...(who?{authorization:'Bearer '+who}:{}),...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})}));return {status:r.status,data:await r.json(),headers:r.headers};};return {store,call,handle};}
const event=(x={})=>({event_id:'field_fixture_1',source_revision:1,learner_id:'lrn_fixture',course_id:'MM12',project_id:'PS-TRUCK-AD',canonical_id:'TA-MM-C1',criterion_id:'TA-MM-C1',rubric_id:'MM12-TRUCK-AD-R1',rubric_version:C.catalogue.rubrics.find(r=>r.id==='MM12-TRUCK-AD-R1').version,outcome_codes_raw:'MM12-1.1',evidence_type_raw:'Observation',stream:'evidence',teacher_note:'Fictional: explained mask revision.',timestamp:'2026-09-24T12:00:00Z',...x});
async function ready(h){await h.call('roster',{course_id:'MM12',learners:[{learner_id:'lrn_fixture',display_name:'Fictional Preview',active:true}]},'google');await h.call('rubric',{course_id:'MM12',rubric_id:'MM12-TRUCK-AD-R1',rubric_version:C.catalogue.rubrics.find(r=>r.id==='MM12-TRUCK-AD-R1').version,confirmed:true});}
test('field endpoint is private, Google-only and empty without a capture',async()=>{const h=setup();assert.equal((await h.call('field-events',null,null)).status,401);assert.equal((await h.call('field-events')).status,403);const r=await h.call('field-events',null,'google');assert.equal(r.status,200);assert.deepEqual(r.data.events,[]);});
test('a field capture retains grouping and reviewed text in the Google mirror, without creating a grade',async()=>{const h=setup();await ready(h);const release=C.catalogue.rubrics.find(r=>r.id==='MM12-TRUCK-AD-R1');const crit=release.criteria[0];const e=event({criterion_id:crit.id,canonical_id:crit.id,outcome_codes_raw:crit.outcome_codes.join(';'),assessment_session_id:'session_1',voice_note_id:'voice_1',transcript_text:'Fictional reviewed text',transcript_reviewed:true,tutorial_skill_ids:crit.skill_ids||[],independence_raw:'Guided',level_raw:'Secure'});const save=await h.call('events',{events:[e]});assert.equal(save.status,200);assert.equal(save.data.results[e.event_id].ok,true);const mirror=(await h.call('field-events',null,'google')).data;assert.equal(mirror.events[0].transcript_text,e.transcript_text);assert.equal(mirror.events[0].assessment_session_id,'session_1');assert.equal(mirror.events[0].support_signal.band,'Guided');assert.equal((await h.call('snapshot')).data.progress.length,0);assert.equal((await h.call('events',{events:[e]})).data.results[e.event_id].dedup,true);});
test('field capture rejects a fictional learner outside the real course roster',async()=>{const h=setup();await ready(h);const crit=C.catalogue.rubrics.find(r=>r.id==='MM12-TRUCK-AD-R1').criteria[0];const r=await h.call('events',{events:[event({learner_id:'lrn_not_enrolled',criterion_id:crit.id,outcome_codes_raw:crit.outcome_codes.join(';')})]});assert.equal(r.status,400);});
test('unreviewed transcripts cannot be submitted as field evidence',()=>{assert.throws(()=>C.normalizeEvent(event({transcript_text:'Unreviewed',transcript_reviewed:false}),'field'),/review/i);});
test('rubric authoring needs explicit confirmation, mapped outcomes and four completed descriptors',async()=>{const h=setup();const r={id:'CUSTOM-FIXTURE',course:'MM12',title:'Preview draft',project_id:'PS-TRUCK-AD',criteria:[{id:'fixture-c',name:'Explanation',skill_ids:['PS-LAY-01'],collection:'Conversation: explain the controlling mask.',outcome_codes:['MM12-1.1'],descriptors:{Beginning:'Partial',Developing:'Some accuracy',Secure:'Accurate',Extending:'Insightful'}}]};assert.equal((await h.call('rubric-publish',r)).status,400);const a=await h.call('rubric-publish',{...r,confirmed:true});assert.equal(a.status,200);const repeat=await h.call('rubric-publish',{...r,confirmed:true});assert.equal(repeat.data.rubric.version,a.data.rubric.version);const b=await h.call('rubric-publish',{...r,confirmed:true,title:'Changed title'});assert.notEqual(b.data.rubric.version,a.data.rubric.version);assert.equal((await h.call('snapshot')).data.rubrics.length,2);});
test('field pagination rejects malformed limits and cursors',async()=>{const h=setup();assert.equal((await h.call('field-events',null,'google','course_id=MM12&limit=no')).status,400);assert.equal((await h.call('field-events',null,'google','course_id=MM12&cursor=missing')).status,409);});
const vm=require('node:vm'),fs=require('node:fs');
function googleMirror(){
 const prepared=JSON.parse(fs.readFileSync('outputs/connected-system-handoff-2026-09-23/GOOGLE_SHEET_FIELD_SETUP.json')).sheets.find(s=>s.title==='Field Evidence').headers;
 const rows=[['private_extra',...prepared.slice().reverse()]];
 const sheet={getLastRow:()=>rows.length,getLastColumn:()=>rows[0].length,setFrozenRows(){},getRange(r,c,n,w){return {getValues:()=>Array.from({length:n},(_,i)=>Array.from({length:w},(_,j)=>rows[r-1+i]?.[c-1+j]??'')),setValues(values){values.forEach((row,i)=>{rows[r-1+i]||=[];row.forEach((v,j)=>rows[r-1+i][c-1+j]=v);});},setFontWeight(){return this},setBackground(){return this},setFontColor(){return this}};}};
 const context={};vm.createContext(context);vm.runInContext(fs.readFileSync('integrations/technology-evidence-system/ConnectedEvidence.gs','utf8'),context);context.ecSheet_=()=>({getSheetByName:()=>sheet});return {context,rows,headers:rows[0]};
}
test('actual Google mirror respects reordered headers, keeps extra columns and upserts revisions without duplicates',()=>{
 const g=googleMirror(),h=g.headers;const e=C.normalizeEvent(event({teacher_note:' =unsafe',level_raw:'Secure',independence_raw:'Guided'}),'field');
 const roster=[{course_id:'MM12',learner_id:'lrn_fixture',display_name:'Fictional Preview'}];
 g.context.ecFieldMirror_([e],roster);assert.equal(g.rows.length,2);assert.equal(g.rows[1][h.indexOf('evidence_note')],"'=unsafe");assert.equal(g.rows[1][h.indexOf('suggested_achievement')],'Secure');assert.equal(g.rows[1][h.indexOf('support_context')],'Guided');g.rows[1][0]='preserved';
 g.context.ecFieldMirror_([{...e,source_revision:2,teacher_note:'Corrected',conflict:true}],roster);g.context.ecFieldMirror_([e],roster);
 assert.equal(g.rows.length,2);assert.equal(g.rows[1][0],'preserved');assert.equal(g.rows[1][h.indexOf('evidence_note')],'Corrected');assert.equal(g.rows[1][h.indexOf('suggested_achievement')],'CONFLICT');
});
test('old Google events keep the installed revision hash',()=>{
 const e={event_id:'review-fixture-01',learner_id:'lrn_review_fixture',course_id:'MM12',project_id:'PS-TRUCK-AD',canonical_id:'TA-OBS-01',outcome_codes_raw:'MM12 1.1',evidence_type_raw:'Observation+Conversation',stream:'evidence',teacher_note:'Fictional review fixture.',level_raw:'Secure',independence_raw:'Guided',teacher_verified:false,timestamp:'2026-09-23T12:00:00Z'};
 assert.equal(C.normalizeEvent(e).revision_id,'30837806935b22bdfb86dfbc521991624ffd1fe4f4d4e8a095727217fe37dea0');
});
test('mirror receipts require Google and the teacher receives the exact mirrored revision',async()=>{const h=setup();const body={course_id:'MM12',receipts:[{event_id:'field_fixture_1',revision_id:'abc'}]};assert.equal((await h.call('mirror-status',body)).status,403);assert.equal((await h.call('mirror-status',body,'google')).status,200);assert.equal((await h.call('mirror-status')).data.receipts[0].revision_id,'abc');});
test('session status exposes expiry without exposing the access key',async()=>{const h=setup();const login=await h.call('login',{access_key:'teacher'},null);const cookie=login.headers.get('set-cookie').split(';')[0];const response=await h.handle(new Request('https://example.test/?action=status',{headers:{cookie}}));const body=await response.json();assert.equal(body.role,'teacher');assert.ok(body.expires_at>Date.now());assert.equal(body.access_key,undefined);});
test('actual Google job paginates separately and acknowledges only written rows',()=>{
 const code=fs.readFileSync('integrations/technology-evidence-system/ConnectedEvidence.gs','utf8'),urls=[],props=new Map(),written=[];let mirrorBeforeAck=false;
 const context={Date,EM:{PROPS:{secret:'test'}},emProp_:()=> 'fake-google-key',PropertiesService:{getScriptProperties:()=>({getProperty:k=>props.get(k),setProperty:(k,v)=>props.set(k,v),deleteProperty:k=>props.delete(k)})},SpreadsheetApp:{flush(){}},UrlFetchApp:{fetch(url,options){const u=new URL(url);urls.push(u);let data={};if(u.searchParams.get('action')==='field-events')data=u.searchParams.get('course_id')==='MM12'&&!u.searchParams.has('cursor')?{events:[{event_id:'page1',revision_id:'rev1'}],has_more:true,next_cursor:'page1'}:{events:[],has_more:false};if(u.searchParams.get('action')==='mirror-status')mirrorBeforeAck=written.includes('page1');return {getResponseCode:()=>200,getContentText:()=>JSON.stringify(data)};}}};
 vm.createContext(context);vm.runInContext(code,context);context.ecFieldMirror_=events=>written.push(...events.map(e=>e.event_id));const result=context.ecSyncField_([]);assert.equal(result.count,1);assert.equal(mirrorBeforeAck,true);const second=urls.find(u=>u.searchParams.get('cursor')==='page1');assert.equal(second.searchParams.get('action'),'field-events');assert.equal(props.size,0);
});
const {stripTypeScriptTypes}=require('node:module');
function client(bindings={}){let code=stripTypeScriptTypes(fs.readFileSync('field-app/src/utils/evidenceBridge.ts','utf8'),{mode:'strip'}).replace(/import\s+[\s\S]*?\sfrom\s+['"][^'"]+['"];?/g,'').replace(/\bexport\s+/g,'');const context={console,Date,JSON,Math,Promise,URL,Response,Event,navigator:{onLine:true},window:{dispatchEvent(){}},...bindings};vm.runInNewContext(code+'\nthis.client=evidenceBridge;',context);return context.client;}
test('installed client cannot enable simulated sync and refuses to cache a wrong-course snapshot',async()=>{let cached=false;const b=client({fetch:async()=>new Response(JSON.stringify({role:'teacher',course_id:'COM11',roster:{learners:[]},rubrics:[]})),cacheRoster:async()=>{cached=true},cacheApprovedRubrics:async()=>{cached=true}});assert.throws(()=>b.setDemoMode(true),/disabled/);assert.equal((await b.fetchCourseSnapshot('MM12')).ok,false);assert.equal(cached,false);});
test('installed serializer retains rubric session, reviewed transcript and support fields',async()=>{let sent;const b=client({fetch:async(url,options)=>{sent=JSON.parse(options.body);return new Response(JSON.stringify({results:{}}));}});await b.submitEventsBatch([event({assessment_session_id:'session_fixture',voice_note_id:'voice_fixture',transcript_text:'Reviewed statement',transcript_reviewed:true,comment_draft_id:'draft_fixture',independence_raw:'Guided'})]);const e=sent.events[0];assert.equal(e.transcript_text,'Reviewed statement');assert.equal(e.transcript_reviewed,true);assert.equal(e.assessment_session_id,'session_fixture');assert.equal(e.independence_raw,'Guided');assert.equal(e.teacher_verified,false);});
test('installed queue keeps evidence without a valid server revision receipt',async()=>{let confirmed=0;const b=client({getPendingEvents:async()=>[event()],markEventConfirmed:async()=>confirmed++,markEventError:async()=>{},fetch:async()=>new Response(JSON.stringify({results:{field_fixture_1:{ok:true}}}))});const r=await b.syncPendingQueue();assert.equal(confirmed,0);assert.equal(r.syncedCount,0);assert.equal(r.errorCount,1);});
test('Gemini adapter requires authenticated teacher access and does not invent success when unconfigured',async()=>{const code=stripTypeScriptTypes(fs.readFileSync('netlify/functions/field-assist.mts','utf8'),{mode:'strip'}).replace(/import service from[^;]+;/,'').replace('export default async','this.handle=async').replace('export const config','const config');const context={service:S,Request,Response,URL,AbortSignal,Netlify:{env:{get:k=>k==='EVIDENCE_MAP_PREVIEW_TEACHER_SECRET'?'teacher':undefined}}};vm.runInNewContext(code,context);const anon=await context.handle(new Request('https://example.test/api/ai/assist',{method:'POST',body:'{}'}));assert.equal(anon.status,401);const signed=await context.handle(new Request('https://example.test/api/ai/assist',{method:'POST',headers:{authorization:'Bearer teacher'},body:'{}'}));assert.equal(signed.status,503);assert.equal((await signed.json()).success,false);});
test('adapting the actual Truck Ad rubric preserves its registered PS/GD skills',()=>{const original=structuredClone(C.catalogue.rubrics.find(r=>r.id==='MM12-TRUCK-AD-R1'));const r=C.normalizeRubric({...original,id:'MM12-PREVIEW-ADAPT',confirmed:true});assert.deepEqual(r.criteria[0].skill_ids,original.criteria[0].skill_ids);});
test('Google mirror preserves the complete contextual support record in its existing column',()=>{
 const g=googleMirror(),detail={dimension_id:'LI-D02',level:2,context:'A changed brief',barrier:'Sequence unclear',strategy:'Short checklist',result:'Helped',next_action:'Try next step'};
 const e=C.normalizeEvent(event({event_id:'support-google-fixture',stream:'support',level_raw:null,canonical_id:'LI-D02',outcome_codes_raw:'',support_detail:detail}),'field');
 g.context.ecFieldMirror_([e],[]);assert.deepEqual(JSON.parse(g.rows[1][g.headers.indexOf('support_context')]),detail);assert.equal(g.rows[1][g.headers.indexOf('suggested_achievement')],'');
});

test('field queue rejects mismatched or malformed receipts without removing pending evidence',async()=>{
 for(const receipt of [{ok:true,record_id:'another-event',revision_id:'a'.repeat(64)},{ok:true,record_id:'field_fixture_1',revision_id:'not-a-hash'},{ok:true,revision_id:'a'.repeat(64)}]){
  let confirmed=0;
  const b=client({getPendingEvents:async()=>[event()],markEventConfirmed:async()=>confirmed++,markEventError:async()=>{},fetch:async()=>new Response(JSON.stringify({results:{field_fixture_1:receipt}}))});
  const r=await b.syncPendingQueue();assert.equal(confirmed,0);assert.equal(r.errorCount,1);
 }
});
test('lost response retains the capture; retry confirms once and only the matching Google revision is mirrored',async()=>{
 let pending=[event()],confirmed=[],attempt=0,mirrorRevision='b'.repeat(64);
 const revision='a'.repeat(64),b=client({getPendingEvents:async()=>pending,getConfirmedEvents:async()=>confirmed,markEventError:async()=>{},markEventConfirmed:async(e,revision_id)=>{pending=pending.filter(p=>p.event_id!==e.event_id);confirmed=[{...e,revision_id}];},fetch:async url=>{
  if(url.includes('mirror-status'))return new Response(JSON.stringify({course_id:'MM12',receipts:[{event_id:'field_fixture_1',revision_id:mirrorRevision}]}));
  if(!attempt++)throw Error('Connection dropped after server accepted request');
  return new Response(JSON.stringify({results:{field_fixture_1:{ok:true,record_id:'field_fixture_1',revision_id:revision,dedup:true}}}));
 }});
 assert.equal((await b.syncPendingQueue()).errorCount,1);assert.equal(pending.length,1);
 assert.equal((await b.syncPendingQueue()).syncedCount,1);assert.equal(pending.length,0);assert.equal(confirmed.length,1);
 await b.updateMirrorReceipts();assert.notEqual(confirmed[0].google_mirror_status,'mirrored');
 mirrorRevision=revision;await b.updateMirrorReceipts();assert.equal(confirmed[0].google_mirror_status,'mirrored');
});
test('backup-storage quota failure preserves the pending capture',async()=>{
 let code=stripTypeScriptTypes(fs.readFileSync('field-app/src/utils/indexedDb.ts','utf8'),{mode:'strip'}).replace(/import\s+[\s\S]*?\sfrom\s+['"][^'"]+['"];?/g,'').replace(/\bexport\s+/g,'');
 const data=new Map([['pending_event_field_fixture_1',JSON.stringify(event())]]),context={console,window:{},catalogueData:{},localStorage:{getItem:k=>data.get(k),removeItem:k=>data.delete(k),setItem(){throw Error('Quota exceeded');}}};
 vm.runInNewContext(code+'\nthis.confirm=markEventConfirmed;',context);
 await assert.rejects(context.confirm(event(),'a'.repeat(64)),/Quota/);
 assert.ok(data.has('pending_event_field_fixture_1'));
});
