const {test}=require('node:test'),assert=require('node:assert/strict');const {create,KEY}=require('../app-storage.js');const Backup=require('../backup-core.js');
function memory(seed={}){const m=new Map(Object.entries(seed));return {getItem:k=>m.has(k)?m.get(k):null,setItem(k,v){m.set(k,v);},dump:()=>Object.fromEntries(m)};}
test('one atomic commit migrates old keys without changing them',()=>{const s=memory({tos_evidence_v1:'{"before":1}',em_studio_v1:'{}'}),a=create(s);assert.equal(a.commit({tos_evidence_v1:'{"after":2}',em_studio_v1:'{"new":1}'}).ok,true);assert.equal(s.getItem('tos_evidence_v1'),'{"before":1}');assert.equal(create(s).getItem('tos_evidence_v1'),'{"after":2}');});
test('quota failure preserves every durable field and supplies unsaved recovery',()=>{const s=memory(),a=create(s);a.commit({tos_evidence_v1:'{}',em_studio_v1:'{}'});const before=s.dump();s.setItem=()=>{throw Error('QuotaExceeded');};assert.equal(a.commit({tos_evidence_v1:'{"new":1}',em_studio_v1:'{"new":2}'}).ok,false);assert.deepEqual(s.dump(),before);assert.ok(JSON.parse(a.recovery()).unsaved);});
test('full replacement removes absent configuration in the same commit',()=>{const s=memory(),a=create(s);a.commit({tos_evidence_v1:'{}',tos_rubrics_v1:'{"old":1}'});a.commit({tos_evidence_v1:'{"restored":1}'},{replace:true});assert.equal(a.getItem('tos_rubrics_v1'),null);});
test('a stale tab cannot overwrite a newer revision',()=>{const s=memory(),a=create(s),b=create(s);a.commit({tos_evidence_v1:'{"first":1}'});assert.equal(b.commit({tos_evidence_v1:'{"second":1}'}).ok,false);assert.equal(create(s).getItem('tos_evidence_v1'),'{"first":1}');});
test('malformed canonical storage is write-blocked until explicit recovery',()=>{const s=memory({[KEY]:'not json'}),a=create(s);assert.ok(a.problem);assert.equal(a.commit({tos_evidence_v1:'{}'}).ok,false);assert.equal(s.getItem(KEY),'not json');assert.equal(a.commit({tos_evidence_v1:'{}'},{replace:true,recover:true}).ok,true);});
const courses={MM12:{modules:[{tag:'M1',outcomes:[{id:'1.1'}]}]}},base=()=>({app:'outcome-evidence-map',schema:1,courses:[{key:'MM12'}],students:{MM12:[{student_id:'ID-1',name:'Synthetic',imported:true}]},evidence:[],judgments:[],legacy_state:{MM12:{'ID-1':{'M1|1.1':{level:3,conf:2,evidence:[{f:'Obs',date:'2026-09-14',note:'Repaired a mask',level:3,criteria:{0:3}}]}}}}});const validate=d=>Backup.validate(d,courses,{},()=>4,()=>[]);
test('nested legacy records reject null, wrong method, dates, levels and unknown keys',()=>{assert.deepEqual(validate(base()),[]);for(const change of [()=>null,e=>({...e,f:'Bogus'}),e=>({...e,date:'2026-02-31'}),e=>({...e,level:8}),e=>({...e,criteria:{0:'3'}})]){const d=base();d.legacy_state.MM12['ID-1']['M1|1.1'].evidence=[change(d.legacy_state.MM12['ID-1']['M1|1.1'].evidence[0])];assert.ok(validate(d).length);}const d=base();d.legacy_state.MM12['ID-1']['M9|9.9']=d.legacy_state.MM12['ID-1']['M1|1.1'];assert.ok(validate(d).length);});
test('shared evidence references must resolve to the same learner and course',()=>{const d=base();d.legacy_state.MM12['ID-1']['M1|1.1'].evidence=[{ref:'E1'}];assert.ok(validate(d).length);d.studio={evidence:[{id:'E1',student:'ID-2',course:'MM12'}]};assert.ok(validate(d).length);});
test('valid shared references and assessed outcome arrays restore; malformed settings do not',()=>{const d=base();d.legacy_state.MM12['ID-1']['M1|1.1'].evidence=[{ref:'E1'}];d.studio={evidence:[{id:'E1',student:'ID-1',course:'MM12',verified:true,outcomeLinks:[{key:'M1|1.1'}]}]};d.assessed_overrides={MM12:{task:['1.1']}};assert.deepEqual(validate(d),[]);d.assessed_overrides.MM12.task=true;assert.ok(validate(d).length);delete d.assessed_overrides;d.rubrics={MM12:{'1.1|Obs':[{label:3}]}};assert.ok(validate(d).length);});
test('invalid legacy JSON is preserved and blocks migration writes',()=>{const s=memory({em_studio_v1:'not json'}),a=create(s);assert.ok(a.problem);assert.equal(a.commit({tos_evidence_v1:'{}'}).ok,false);assert.equal(s.getItem('em_studio_v1'),'not json');});
