(function(root){
  'use strict';
  const K=root.CatalogueCore;
  const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const $=s=>document.querySelector(s);
  const $$=s=>[...document.querySelectorAll(s)];
  let selectedId=null,search='',status='all',sprintFilter='';
  const button=(label,attr,value,cls='ghost')=>`<button class="btn ${cls}" ${attr}="${esc(value)}">${esc(label)}</button>`;
  const notes=b=>b.issues.map(i=>`<li>${esc(i.message)}</li>`).join('');
  function rubricHTML(r){
    if(!r)return '<p class="notice warn">The specified task rubric is not available. You can collect descriptive observations, but this page cannot supply a task-specific markscheme yet.</p>';
    return `<p class="hint">${esc(r.title||r.id)} · ${esc(r.type)}. No automatic percentage or predicted IB grade.</p>`+(r.criteria||[]).map(c=>`<details><summary>${esc(c.name)}</summary><div class="table-wrap"><table><thead><tr><th>Descriptor</th><th>Observable evidence</th></tr></thead><tbody>${Object.entries(c.descriptors||{}).map(([band,text])=>`<tr><th>${esc(band)}</th><td>${esc(text)}</td></tr>`).join('')}</tbody></table></div>${c.collection?'<p><b>Collect:</b> '+esc(c.collection)+'</p>':''}${c.repair?'<p><b>Repair:</b> '+esc(c.repair)+'</p>':''}</details>`).join('')+`<p class="hint">${esc(r.missing||r.insufficient_evidence||'Insufficient evidence stays blank.')}</p>`;
  }
  function detail(b,ctx){
    const a=b.assignment,records=K.evidenceFor(b,ctx.evidence),known=new Map(ctx.students.map(s=>[s.id,s.name]));
    return `<section class="panel assignment-detail" id="assignmentDetail" tabindex="-1" aria-labelledby="assignmentTitle"><div class="kicker">Assignment / ${esc(a.id)}</div><h3 id="assignmentTitle">${esc(a.title)}</h3><div class="lesson-meta"><span class="pill">${b.ready?'Package verified':'Needs preparation'}</span><span class="pill">${esc(a.purpose||'Planned')} · ${esc(a.method||'Evidence method to review')}</span><span class="pill">${esc(a.date||'Unscheduled')}</span></div><p class="hint">Catalogue ${esc(b.version)}. Dates are planning dates; no student score is inferred.</p>${b.issues.length?'<div class="notice warn"><b>Before using this as an assessment</b><ul>'+notes(b)+'</ul></div>':''}<div class="actions">${button('Record evidence for this assignment','data-assignment-capture',a.id,'primary')}${button('Download fabrication brief','data-assignment-brief',a.id)}${button('Show linked sprint','data-assignment-sprint',b.sprintIds[0]||'')}</div><h4>Outcomes and I-can statements</h4>${b.targets.map(o=>`<div class="record"><b>${esc(o.code||o.id)} · ${esc(o.label)}</b>${o.statement?'<p>'+esc(o.statement)+'</p>':''}<p class="hint">${esc(o.authority||'Reference unresolved')}${o.resolved&&!o.key?' · Not connected to the active outcome capture register':''}</p></div>`).join('')||'<p>No outcome references supplied.</p>'}<h4>Task rubric</h4>${rubricHTML(b.rubric)}<h4>Teaching-package checklist</h4><p class="hint">Verification requires a component reference, reviewer and date. Marking a lesson taught does not complete this checklist.</p><div class="package-checks">${b.materials.map(m=>`<div><span aria-hidden="true">${m.verified?'✓':'○'}</span><div><b>${esc(m.label)}</b><p>${m.verified?'Verified reference: '+esc(m.reference):'Not verified'}</p></div></div>`).join('')}</div><h4>Linked lessons (${b.lessons.length})</h4>${b.lessons.map(l=>ctx.lessonHTML(l)).join('')||'<p>Link the lesson specifications before fabricating.</p>'}<h4>Evidence collected for this assignment</h4><p class="hint">Teacher workspace · ${records.filter(r=>r.verified).length} verified records; ${records.filter(r=>!r.verified).length} unverified claims/observations. Counts are not grades. Only active records in this course with a matching assignment ID are shown.</p>${records.map(r=>`<div class="record"><b>${esc(known.get(r.student)||'Learner no longer on current roster')} · ${esc(r.method)} · ${esc(r.date)}</b><p>${esc(r.note)}</p><p class="hint">${r.verified?'Teacher verified':'Unverified'} · ${esc(r.artifact||'No artifact reference')} · ${esc(r.support)}${r.rubricId?' · Rubric reference at capture: '+esc(r.rubricId):''}</p>${r.next?'<p><b>Next:</b> '+esc(r.next)+'</p>':''}</div>`).join('')||'<p>No evidence linked yet. Start with a specific observed action, conversation or product.</p>'}</section>`;
  }
  function bind(ctx,bundles){
    $$('[data-open-assignment]').forEach(b=>b.onclick=()=>{selectedId=b.dataset.openAssignment;render(ctx);$('#assignmentDetail')?.focus();});
    $$('[data-assignment-brief]').forEach(b=>b.onclick=()=>{const item=bundles.find(x=>x.assignment.id===b.dataset.assignmentBrief);ctx.download(K.brief(item),item.assignment.id+'-fabrication.md');});
    $$('[data-assignment-capture]').forEach(b=>b.onclick=()=>ctx.capture(bundles.find(x=>x.assignment.id===b.dataset.assignmentCapture)));
    $$('[data-assignment-sprint]').forEach(b=>b.onclick=()=>{sprintFilter=b.dataset.assignmentSprint;ctx.route('sprintoverview');});
    $$('[data-sprint-assignments]').forEach(b=>b.onclick=()=>{sprintFilter=b.dataset.sprintAssignments;selectedId=null;search='';status='all';ctx.route('assignments');});
    $('#earlierAssessments')?.addEventListener('click',()=>ctx.route('assessment'));
    $('#earlierSprints')?.addEventListener('click',()=>ctx.route('sprints'));
    ctx.bindLessons();
  }
  function render(ctx){
    const all=K.bundles(ctx.data,ctx.course,ctx.outcomes,ctx.lessons);
    if(!all.length){ctx.frame(ctx.intro('Assignments and rubrics','There is no consolidated assignment catalogue for this course.')+`<div class="panel"><p>Existing course records remain available.</p><button class="btn primary" id="earlierAssessments">Open existing assessment design</button></div>`);bind(ctx,all);return;}
    const filtered=all.filter(b=>(!search||[b.assignment.id,b.assignment.title,...b.targets.map(t=>t.label)].join(' ').toLowerCase().includes(search.toLowerCase()))&&(!sprintFilter||b.sprintIds.includes(sprintFilter))&&(status==='all'||status==='missing'&&!b.rubric||status==='ready'&&b.ready||status==='unready'&&!b.ready));
    const selected=filtered.find(b=>b.assignment.id===selectedId)||filtered[0];selectedId=selected?.assignment.id||null;
    const summary=`<div class="catalogue-stats"><div><strong>${all.length}</strong><span>planned assessments</span></div><div><strong>${all.filter(b=>!!b.rubric).length}</strong><span>rubrics linked</span></div><div><strong>${all.filter(b=>b.ready).length}</strong><span>packages verified</span></div><div><strong>${all.filter(b=>b.issues.some(i=>i.code==='outcomes')).length}</strong><span>target reviews needed</span></div></div>`;
    const filters=`<div class="formgrid"><div><label for="assignmentSearch">Find assignment or outcome</label><input id="assignmentSearch" type="search" value="${esc(search)}"></div><div><label for="assignmentStatus">Preparation status</label><select id="assignmentStatus">${[['all','All assignments'],['missing','Rubric missing'],['unready','Needs preparation'],['ready','Package verified']].map(([v,t])=>`<option value="${v}" ${status===v?'selected':''}>${t}</option>`).join('')}</select></div><div><label for="assignmentSprint">Linked sprint</label><select id="assignmentSprint"><option value="">All sprints</option>${[...new Set(all.flatMap(b=>b.sprintIds))].sort().map(id=>`<option ${id===sprintFilter?'selected':''}>${esc(id)}</option>`).join('')}</select></div></div>`;
    ctx.frame(ctx.intro('Assignments and rubrics','The dated assessment catalogue connects lesson specifications, outcomes, available rubrics and teacher evidence. Missing dependencies stay visible.')+summary+`<div class="actions"><button class="btn ghost" id="assignmentExport">Download preparation register CSV</button><button class="btn ghost" id="earlierAssessments">Earlier assessment design</button></div>`+filters+`<p class="hint" role="status">${filtered.length} assignments shown. Existing evidence and earlier plans are preserved.</p><div class="assignment-layout"><div class="assignment-list" aria-label="Assignments">${filtered.map(b=>`<button class="assignment-choice ${selectedId===b.assignment.id?'selected':''}" data-open-assignment="${esc(b.assignment.id)}" aria-pressed="${selectedId===b.assignment.id}"><span class="lesson-id">${esc(b.assignment.id)}</span><b>${esc(b.assignment.title)}</b><span>${esc(b.assignment.date||'Unscheduled')} · ${b.rubric?'Rubric linked':'Rubric missing'}</span><span>${b.ready?'Package verified':'Needs preparation'}</span></button>`).join('')||'<p>No assignments match. Change the filters.</p>'}</div><div>${selected?detail(selected,ctx):''}</div></div>`);
    $('#assignmentSearch').onchange=e=>{search=e.target.value;render(ctx);};$('#assignmentStatus').onchange=e=>{status=e.target.value;render(ctx);};$('#assignmentSprint').onchange=e=>{sprintFilter=e.target.value;render(ctx);};
    $('#assignmentExport').onclick=()=>ctx.download(ctx.csv([['assignment_id','title','date','rubric_reference','rubric_linked','package_verified','sprints','outcomes','required_repairs'],...all.map(b=>[b.assignment.id,b.assignment.title,b.assignment.date,b.assignment.rubric,!!b.rubric,b.ready,b.sprintIds.join('; '),b.targets.map(o=>o.id).join('; '),b.issues.map(i=>i.message).join('; ')])]),ctx.course+'-assignment-preparation.csv','text/csv');
    bind(ctx,all);
  }
  function sprints(ctx){
    const all=K.bundles(ctx.data,ctx.course,ctx.outcomes,ctx.lessons),sprints=ctx.data.sprints.filter(s=>s.course===ctx.course);
    ctx.frame(ctx.intro('Sprint overview','Compare the newer sprint architecture with the current dated lessons and their assignments. Architecture is a proposal; the dated plan contains later revisions.')+`<div class="notice warn">Names or commissions may differ between versions, especially the opening Citrus revision. Review the linked dated lessons before choosing the final teaching package. The architecture does not overwrite your planning edits.</div><div class="actions"><button class="btn ghost" id="earlierSprints">Earlier sprint planner</button></div><div class="sprint-catalogue">${sprints.map(s=>{const lessons=ctx.lessons.filter(l=>l.course===ctx.course&&l.sequence==='dated'&&K.sprintId(l)===s.id),assignments=all.filter(b=>b.sprintIds.includes(s.id));return `<section class="panel ${sprintFilter===s.id?'sprint-selected':''}"><div class="kicker">${esc(s.id)} · ${s.periods} planned periods</div><h3>${esc(s.title)}</h3><span class="pill">Architecture proposal</span><p><b>Builds on:</b> ${esc(s.builds_on)}</p><p><b>New learning:</b> ${esc(s.new_learning)}</p><p><b>Commission:</b> ${esc(s.commission)}</p><p><b>Lab:</b> ${esc(s.lab)}</p><p><b>Independent evidence:</b> ${esc(s.independent_evidence)}</p><p class="hint">${lessons.length} dated lessons · ${assignments.length} linked assignments · ${assignments.filter(b=>b.ready).length} verified packages</p>${button('Open linked assignments','data-sprint-assignments',s.id,'primary')}<details><summary>Current dated lesson titles</summary>${lessons.map(l=>'<p>'+esc(l.date||'Unscheduled')+' · '+esc(l.title)+'</p>').join('')||'<p>No dated lessons linked.</p>'}</details></section>`;}).join('')||'<p>No consolidated sprints for this course. Use the existing planner.</p>'}</div>`);bind(ctx,all);
  }
  root.AssignmentStudio={render,sprints,open(id){selectedId=id;search='';status='all';sprintFilter='';},reset(){selectedId=null;search='';status='all';sprintFilter='';}};
})(window);
